### ISSUE TITLE
author facets number does not correspond with number of results

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#553]
The number shown in the Author facet:

![screen shot 2015-11-24 at 1 28 27 pm](https://cloud.githubusercontent.com/assets/580727/11366709/4a571d68-92af-11e5-803a-87cccd3f7073.png)

Does not correspond with the number of results that the user gets back when clicking on one facet value.

This only seems to happen in the Author facet.

**Comment by jmartinm** [comment]
@ioannistsanaktsidis can you look into this?

**Comment by ioannistsanaktsidis** [comment]
Yes sure!

**Comment by ioannistsanaktsidis** [comment]
<img width="294" alt="screen shot 2015-11-27 at 10 24 49" src="https://cloud.githubusercontent.com/assets/7301890/11437902/76eca14c-94f1-11e5-91cc-6eafe546685b.png">

After rebasing and updating elasticsearch the problem with the authors is fixed (!??!!). I can't reproduce the problem we had.

**Comment by ioannistsanaktsidis** [comment]
@jmartinm could you also rebase and check this one? If is ok for you also, then we do not have any functional problems with the facets ;)

**Comment by jmartinm** [comment]
I still see the issue. For example:

https://qa.inspirehep.net/search

Click on `Avetisyan, Aram`. That should give 16 results but gives 27.

**Comment by ioannistsanaktsidis** [comment]
True, you are right!

2015-11-30 14:51 GMT+01:00 Javier Martin Montull <notifications@github.com>:
